services:
#  mariadb:
#    image: mariadb:10.9.6
#    platform: linux/amd64
#    environment:
#      MARIADB_ROOT_PASSWORD: mariadb

  postgres:
    image: postgres:15.4
    platform: linux/amd64
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'test_db'
    volumes:
      - ./postgres_init.sql:/docker-entrypoint-initdb.d/init.sql

  mysql:
    image: mysql:8.1.0
    platform: linux/amd64
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: test_db
    volumes:
      - "./mysql_init_01_numbers.sql:/docker-entrypoint-initdb.d/mysql_init_01_numbers.sql"
      - "./mysql_init_02_client.sql:/docker-entrypoint-initdb.d/mysql_init_02_client.sql"
      - "./mysql_init_03_order.sql:/docker-entrypoint-initdb.d/mysql_init_03_order.sql"
      - "./mysql_init_04_product.sql:/docker-entrypoint-initdb.d/mysql_init_04_product.sql"
      - "./mysql_init_05_order_detail.sql:/docker-entrypoint-initdb.d/mysql_init_05_order_detail.sql"
      - "./mysql_init_06_filter_10m.sql:/docker-entrypoint-initdb.d/mysql_init_06_filter_10m.sql"
      - "./mysql_init_07_filter_1m.sql:/docker-entrypoint-initdb.d/mysql_init_07_filter_1m.sql"
      - "./mysql_init_08_large_group_by_table.sql:/docker-entrypoint-initdb.d/mysql_init_08_large_group_by_table.sql"
      - "./mysql_init_09_group_by_table.sql:/docker-entrypoint-initdb.d/mysql_init_09_group_by_table.sql"

  mssql2022:
    image: mcr.microsoft.com/mssql/server:2022-CU7-ubuntu-20.04
    platform: linux/amd64
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: Y
      MSSQL_USER: SA
      MSSQL_SA_PASSWORD: 'myStrong(!)Password'
      MSSQL_PID: Developer

#  mssql2019:
#    image: mcr.microsoft.com/mssql/server:2019-CU20-ubuntu-20.04
#    platform: linux/amd64
#    ports:
#      - "1434:1433"
#    environment:
#      ACCEPT_EULA: Y
#      MSSQL_USER: SA
#      MSSQL_SA_PASSWORD: 'myStrong(!)Password'
#      MSSQL_PID: Developer
#    volumes:
#      - "./mssql_init.sql:/mssql_init.sql"
#      - "./mssql_init.sh:/mssql_init.sh"
#    command:
#      - /mssql_init.sh
